name: Playwright Auto Tests

on:
  schedule:
    - cron: '0 */3 * * *'   # запуск кожні 3 години
  workflow_dispatch:        # можливість ручного запуску

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CUSTOMER_LOGIN_TEST_LOGIN: ${{ secrets.CUSTOMER_LOGIN_TEST_LOGIN }}
      CUSTOMER_LOGIN_TEST_PASSWORD: ${{ secrets.CUSTOMER_LOGIN_TEST_PASSWORD }}
      CUSTOMER_LOGIN_TEST_FULL_NAME: ${{ secrets.CUSTOMER_LOGIN_TEST_FULL_NAME }}
      BUSINESS_LOGIN_TEST_LOGIN: ${{ secrets.BUSINESS_LOGIN_TEST_LOGIN }}
      BUSINESS_LOGIN_TEST_PASSWORD: ${{ secrets.BUSINESS_LOGIN_TEST_PASSWORD }}
      BUSINESS_LOGIN_TEST_BUSINESS_NAME: ${{ secrets.BUSINESS_LOGIN_TEST_BUSINESS_NAME }}
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🌍 Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: 🚀 Run Playwright Tests
        run: npm run test

      - name: 📤 Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
